/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Client
 */
public class latihankalkulator extends javax.swing.JFrame {
    String angka="";
    double jumlah, angka1,angka2;
    int pilih;
    /**
     * Creates new form latihankalkulator
     */
    public latihankalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        btnhasil = new javax.swing.JButton();
        btnangka8 = new javax.swing.JButton();
        btnkoma = new javax.swing.JButton();
        btnangka0 = new javax.swing.JButton();
        btnkurang = new javax.swing.JButton();
        btnangka9 = new javax.swing.JButton();
        btnangka7 = new javax.swing.JButton();
        btnangka5 = new javax.swing.JButton();
        btnangka1 = new javax.swing.JButton();
        btnangka6 = new javax.swing.JButton();
        btnangka2 = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        btnangka3 = new javax.swing.JButton();
        btnangka4 = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnkali = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        btnpersen = new javax.swing.JButton();
        btnkuadrat = new javax.swing.JButton();
        btnakar = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        btnbagi = new javax.swing.JButton();
        btncos = new javax.swing.JButton();
        btnlog2 = new javax.swing.JButton();
        btnsin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(null);

        display.setEditable(false);
        display.setBackground(new java.awt.Color(102, 102, 102));
        display.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        display.setText("0");
        getContentPane().add(display);
        display.setBounds(10, 0, 350, 140);

        btnhasil.setBackground(new java.awt.Color(51, 51, 51));
        btnhasil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnhasil.setText("=");
        btnhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhasilActionPerformed(evt);
            }
        });
        getContentPane().add(btnhasil);
        btnhasil.setBounds(300, 360, 60, 130);

        btnangka8.setBackground(new java.awt.Color(255, 255, 255));
        btnangka8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnangka8.setText("8");
        btnangka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka8);
        btnangka8.setBounds(160, 220, 60, 60);

        btnkoma.setBackground(new java.awt.Color(204, 204, 204));
        btnkoma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnkoma.setText(".");
        btnkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkomaActionPerformed(evt);
            }
        });
        getContentPane().add(btnkoma);
        btnkoma.setBounds(90, 430, 60, 60);

        btnangka0.setBackground(new java.awt.Color(255, 255, 255));
        btnangka0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnangka0.setText("0");
        btnangka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka0);
        btnangka0.setBounds(160, 430, 60, 60);

        btnkurang.setBackground(new java.awt.Color(102, 102, 102));
        btnkurang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnkurang.setText("-");
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });
        getContentPane().add(btnkurang);
        btnkurang.setBounds(300, 290, 60, 60);

        btnangka9.setBackground(new java.awt.Color(255, 255, 255));
        btnangka9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnangka9.setText("9");
        btnangka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka9);
        btnangka9.setBounds(230, 220, 60, 60);

        btnangka7.setBackground(new java.awt.Color(255, 255, 255));
        btnangka7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnangka7.setText("7");
        btnangka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka7);
        btnangka7.setBounds(90, 220, 60, 60);

        btnangka5.setBackground(new java.awt.Color(255, 255, 255));
        btnangka5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnangka5.setText("5");
        btnangka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka5);
        btnangka5.setBounds(160, 290, 60, 60);

        btnangka1.setBackground(new java.awt.Color(255, 255, 255));
        btnangka1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnangka1.setText("1");
        btnangka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka1);
        btnangka1.setBounds(90, 360, 60, 60);

        btnangka6.setBackground(new java.awt.Color(255, 255, 255));
        btnangka6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnangka6.setText("6");
        btnangka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka6);
        btnangka6.setBounds(230, 290, 60, 60);

        btnangka2.setBackground(new java.awt.Color(255, 255, 255));
        btnangka2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnangka2.setText("2");
        btnangka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka2);
        btnangka2.setBounds(160, 360, 60, 60);

        btntambah.setBackground(new java.awt.Color(102, 102, 102));
        btntambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btntambah.setText("+");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah);
        btntambah.setBounds(230, 430, 60, 60);

        btnangka3.setBackground(new java.awt.Color(255, 255, 255));
        btnangka3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnangka3.setText("3");
        btnangka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka3);
        btnangka3.setBounds(230, 360, 60, 60);

        btnangka4.setBackground(new java.awt.Color(255, 255, 255));
        btnangka4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnangka4.setText("4");
        btnangka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnangka4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnangka4);
        btnangka4.setBounds(90, 290, 60, 60);

        btnclear.setBackground(new java.awt.Color(255, 0, 0));
        btnclear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnclear.setText("C");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear);
        btnclear.setBounds(20, 150, 60, 60);

        btnkali.setBackground(new java.awt.Color(102, 102, 102));
        btnkali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnkali.setText("X");
        btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkali);
        btnkali.setBounds(300, 220, 60, 60);

        jButton30.setBackground(new java.awt.Color(153, 153, 255));
        jButton30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton30.setText("^");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30);
        jButton30.setBounds(20, 430, 60, 60);

        btnpersen.setBackground(new java.awt.Color(153, 153, 255));
        btnpersen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnpersen.setText("%");
        btnpersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersenActionPerformed(evt);
            }
        });
        getContentPane().add(btnpersen);
        btnpersen.setBounds(20, 220, 60, 60);

        btnkuadrat.setBackground(new java.awt.Color(153, 153, 255));
        btnkuadrat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnkuadrat.setText("X^2");
        btnkuadrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkuadratActionPerformed(evt);
            }
        });
        getContentPane().add(btnkuadrat);
        btnkuadrat.setBounds(20, 360, 60, 60);

        btnakar.setBackground(new java.awt.Color(153, 153, 255));
        btnakar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnakar.setText("√");
        btnakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnakarActionPerformed(evt);
            }
        });
        getContentPane().add(btnakar);
        btnakar.setBounds(20, 290, 60, 60);

        btnlog.setBackground(new java.awt.Color(102, 153, 255));
        btnlog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlog.setText("log");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        getContentPane().add(btnlog);
        btnlog.setBounds(90, 150, 60, 60);

        btnbagi.setBackground(new java.awt.Color(102, 102, 102));
        btnbagi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnbagi.setText("/");
        btnbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbagiActionPerformed(evt);
            }
        });
        getContentPane().add(btnbagi);
        btnbagi.setBounds(300, 150, 60, 60);

        btncos.setBackground(new java.awt.Color(102, 153, 255));
        btncos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncos.setText("cos");
        btncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosActionPerformed(evt);
            }
        });
        getContentPane().add(btncos);
        btncos.setBounds(160, 150, 60, 60);

        btnlog2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlog2.setText("log");
        btnlog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlog2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnlog2);
        btnlog2.setBounds(160, 150, 60, 60);

        btnsin.setBackground(new java.awt.Color(102, 153, 255));
        btnsin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsin.setText("sin");
        btnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinActionPerformed(evt);
            }
        });
        getContentPane().add(btnsin);
        btnsin.setBounds(230, 150, 60, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9fca5698bd1390949ad27a506ccef1a8.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-50, 0, 450, 560);

        setBounds(0, 0, 383, 565);
    }// </editor-fold>//GEN-END:initComponents

    private void btnangka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangka2ActionPerformed
        // TODO add your handling code here:
        angka += "2";
        display.setText(angka);
    }//GEN-LAST:event_btnangka2ActionPerformed

    private void btnangka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangka7ActionPerformed
        // TODO add your handling code here:
        angka += "7";
        display.setText(angka);
    }//GEN-LAST:event_btnangka7ActionPerformed

    private void btnangka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangka1ActionPerformed
        // TODO add your handling code here:
        angka += "1";
        display.setText(angka);
    }//GEN-LAST:event_btnangka1ActionPerformed

    private void btnangka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangka0ActionPerformed
        // TODO add your handling code here:
        angka += "0";
        display.setText(angka);
    }//GEN-LAST:event_btnangka0ActionPerformed

    private void btnangka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangka3ActionPerformed
        // TODO add your handling code here:
        angka += "3";
        display.setText(angka);
    }//GEN-LAST:event_btnangka3ActionPerformed

    private void btnangka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangka4ActionPerformed
        // TODO add your handling code here:
        angka += "4";
        display.setText(angka);
    }//GEN-LAST:event_btnangka4ActionPerformed

    private void btnangka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangka5ActionPerformed
        // TODO add your handling code here:
        angka += "5";
        display.setText(angka);
    }//GEN-LAST:event_btnangka5ActionPerformed

    private void btnangka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangka6ActionPerformed
        // TODO add your handling code here:
        angka += "6";
        display.setText(angka);
    }//GEN-LAST:event_btnangka6ActionPerformed

    private void btnangka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangka8ActionPerformed
        // TODO add your handling code here:
        angka += "8";
        display.setText(angka);
    }//GEN-LAST:event_btnangka8ActionPerformed

    private void btnangka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnangka9ActionPerformed
        // TODO add your handling code here:
        angka += "9";
        display.setText(angka);
    }//GEN-LAST:event_btnangka9ActionPerformed

    private void btnkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkomaActionPerformed
        // TODO add your handling code here:
        angka += ".";
        display.setText(angka);
    }//GEN-LAST:event_btnkomaActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        display.setText("");
        angka1=0.0;
        angka2=0.0;
        jumlah=0.0;
        angka="";
    }//GEN-LAST:event_btnclearActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("+");
        angka="";
        pilih=1;
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("-");
        angka="";
        pilih=2;
    }//GEN-LAST:event_btnkurangActionPerformed

    private void btnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaliActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("*");
        angka="";
        pilih=3;
    }//GEN-LAST:event_btnkaliActionPerformed

    private void btnbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbagiActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("/");
        angka="";
        pilih=4;
    }//GEN-LAST:event_btnbagiActionPerformed

    private void btnhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhasilActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
        case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
        case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
        case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);            
            break;
        case 5:
            jumlah = angka1/100;
            angka = Double.toString(jumlah);
            display.setText(angka); 
            break;
        case 6:
            jumlah = Math.pow(angka1, 2);
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
        case 7:
            angka2 = Double.parseDouble(angka);
            jumlah = Math.pow(angka1, angka2);
            angka = Double.toString(jumlah);
            display.setText(angka);  
            break;    
        case 8:    
            jumlah = Math.sqrt(angka1);
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
        case 9:
             angka2 = Double.parseDouble(angka);
            jumlah = Math.log(angka1);
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
        case 10:            
            jumlah = Math.sin(angka1);
            angka = Double.toString(jumlah);
            display.setText(angka); 
            break;
        case 11:            
            jumlah = Math.cos(angka1);
            angka = Double.toString(jumlah);
            display.setText(angka); 
            break;
            default:
            break;
}
    }//GEN-LAST:event_btnhasilActionPerformed

    private void btnpersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersenActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("%");
        angka="";
        pilih=5;
    }//GEN-LAST:event_btnpersenActionPerformed

    private void btnkuadratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkuadratActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("^");
        angka="";
        pilih=6;
    }//GEN-LAST:event_btnkuadratActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("^");
        angka="";
        pilih=7;
    }//GEN-LAST:event_jButton30ActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        // TODO add your handling code here:
            angka1=Double.parseDouble(angka);
            display.setText(" Log ");
            angka="";
            pilih=9; 
    }//GEN-LAST:event_btnlogActionPerformed

    private void btnakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnakarActionPerformed
        // TODO add your handling code here:
         angka1=Double.parseDouble(angka);
        display.setText("√");
        angka="";
        pilih=8;
    }//GEN-LAST:event_btnakarActionPerformed

    private void btncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncosActionPerformed
        // TODO add your handling code here:
         angka1=Double.parseDouble(angka);
            display.setText(" Cos ");
            angka="";
            pilih=11;
        
    }//GEN-LAST:event_btncosActionPerformed

    private void btnlog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlog2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlog2ActionPerformed

    private void btnsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText(" Sin ");
        angka="";
        pilih=10;
    }//GEN-LAST:event_btnsinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihankalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihankalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihankalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihankalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihankalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnakar;
    private javax.swing.JButton btnangka0;
    private javax.swing.JButton btnangka1;
    private javax.swing.JButton btnangka2;
    private javax.swing.JButton btnangka3;
    private javax.swing.JButton btnangka4;
    private javax.swing.JButton btnangka5;
    private javax.swing.JButton btnangka6;
    private javax.swing.JButton btnangka7;
    private javax.swing.JButton btnangka8;
    private javax.swing.JButton btnangka9;
    private javax.swing.JButton btnbagi;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btncos;
    private javax.swing.JButton btnhasil;
    private javax.swing.JButton btnkali;
    private javax.swing.JButton btnkoma;
    private javax.swing.JButton btnkuadrat;
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnlog2;
    private javax.swing.JButton btnpersen;
    private javax.swing.JButton btnsin;
    private javax.swing.JButton btntambah;
    private javax.swing.JTextField display;
    private javax.swing.JButton jButton30;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
